// Text shown in the app: [Hinglish, Hindi, English]. Shared with the web demo (demo/template.html).

export const STRINGS = {
  "tab.chat": ["Baat","बात","Chat"],
  "tab.customers": ["Grahak","ग्राहक","Customers"],
  "tab.stock": ["Stock","स्टॉक","Stock"],
  "tab.shop": ["Dukaan","दुकान","Shop"],
  "placeholder": ["Bolo ya likho…","बोलिए या लिखिए…","Speak or type…"],
  "listening": ["Sun raha hoon… boliye","सुन रहा हूँ… बोलिए","Listening… speak now"],
  "today": ["Aaj","आज","Today"],
  "todayLower": ["aaj","आज","today"],
  "welcome.1": ["Namaste! Main AwaazCRM hoon.","नमस्ते! मैं आवाज़CRM हूँ।","Hello! I am AwaazCRM."],
  "welcome.2": ["Hara mic dabaiye aur boliye, jaise:","हरा माइक दबाइए और बोलिए, जैसे:","Tap the green mic and speak, for example:"],
  "bill.check": ["Bill · check karein","बिल · जाँच करें","Bill · please check"],
  "bill.customer": ["Grahak","ग्राहक","Customer"],
  "bill.total": ["Total · {n} item","कुल · {n} आइटम","Total · {n} item(s)"],
  "bill.paidNow": ["Abhi diye ({m})","अभी दिए ({m})","Paid now ({m})"],
  "bill.onCredit": ["Udhaar mein","उधार में","On credit"],
  "bill.cancel": ["Radd karo","रद्द करें","Cancel"],
  "bill.confirm": ["Haan, pakka karo","हाँ, पक्का करें","Yes, confirm"],
  "bill.done": ["Pakka hua","पक्का हुआ","Confirmed"],
  "bill.cancelled": ["Bill radd kiya","बिल रद्द किया","Bill cancelled"],
  "mode.udhaar": ["UDHAAR","उधार","CREDIT"],
  "mode.cash": ["CASH","नकद","CASH"],
  "mode.upi": ["UPI","UPI","UPI"],
  "m.cash": ["cash","नकद","cash"],
  "m.upi": ["UPI","UPI","UPI"],
  "issue.choose_variant": ["{name}: kaunsa size? Ek tap mein chuniye","{name}: कौन सा साइज़? एक टैप में चुनिए","{name}: which size? Pick with one tap"],
  "issue.unclear": ["Ek item saaf nahi suna. Kaunsa tha?","एक आइटम साफ़ नहीं सुना। कौन सा था?","One item was not clear. Which one was it?"],
  "issue.not_found": ["\"{name}\" saamaan list mein nahi hai","\"{name}\" सामान की सूची में नहीं है","\"{name}\" is not in your item list"],
  "issue.price_missing": ["{name} ka daam nahi pata. Stock tab mein daam daaliye.","{name} का दाम नहीं पता। स्टॉक टैब में दाम डालिए।","No price for {name}. Add it in the Stock tab."],
  "issue.customer_unknown": ["\"{name}\" naam ka grahak nahi mila","\"{name}\" नाम का ग्राहक नहीं मिला","No customer named \"{name}\""],
  "issue.customer_ambiguous": ["\"{name}\" naam ke ek se zyada grahak hain. Kaun?","\"{name}\" नाम के एक से ज़्यादा ग्राहक हैं। कौन?","More than one customer is called \"{name}\". Which one?"],
  "issue.customer_required": ["Udhaar kiske naam likhein?","उधार किसके नाम लिखें?","Whose account should this go on?"],
  "heard": ["Suna","सुना","Heard"],
  "issue.newCustomer": ["+ Naya grahak: {name}","+ नया ग्राहक: {name}","+ New customer: {name}"],
  "issue.noName": ["Bina naam ke","बिना नाम के","Without a name"],
  "remove": ["Hatao","हटाओ","Remove"],
  "issue.newItem": ["+ Naya item: {name}","+ नया आइटम: {name}","+ New item: {name}"],
  "issue.autoAdded": ["{name} naya item hai. Inventory mein jod diya — bas daam bataiye.","{name} नया आइटम है। इन्वेंटरी में जोड़ दिया — बस दाम बताइए।","{name} is a new item. Added to your inventory — just tell me the price."],
  "issue.orPick": ["Ya inme se koi:","या इनमें से कोई:","Or one of these:"],
  "issue.orCustomer": ["Ya pehle se grahak:","या पहले से ग्राहक:","Or an existing customer:"],
  "learn.done": ["Seekh liya: \"{heard}\" matlab {name}. Agli baar seedha samjhunga.","सीख लिया: \"{heard}\" मतलब {name}। अगली बार सीधे समझूँगा।","Learned: \"{heard}\" means {name}. Next time I will get it directly."],
  "learn.title": ["Awaaz sudhaar","आवाज़ सुधार","Voice improvement"],
  "learn.sub": ["Aap jo sudhaarte hain, app yaad rakhta hai — sirf aapki dukaan ke liye.","आप जो सुधारते हैं, ऐप याद रखता है — सिर्फ़ आपकी दुकान के लिए।","What you correct, the app remembers — for your shop only."],
  "learn.names": ["Seekhe hue naam","सीखे हुए नाम","Learned names"],
  "learn.none": ["Abhi kuch nahi seekha. Bill mein galat naam ko sahi item/grahak chunkar sudhaariye.","अभी कुछ नहीं सीखा। बिल में गलत नाम को सही आइटम/ग्राहक चुनकर सुधारिए।","Nothing learned yet. Correct a wrong name on a bill by picking the right item or customer."],
  "learn.forget": ["Bhoolo","भूलो","Forget"],
  "log.title": ["Galat samjhe gaye vakya","गलत समझे गए वाक्य","Misunderstood commands"],
  "log.optin": ["Team ko bhejein taaki app behtar samjhe","टीम को भेजें ताकि ऐप बेहतर समझे","Share with the team so the app understands better"],
  "log.optinSub": ["Sirf woh vakya jo samajh nahi aaye ya sudhaare gaye, 90 din tak. Kabhi bhi band kar sakte hain.","सिर्फ़ वे वाक्य जो समझ नहीं आए या सुधारे गए, 90 दिन तक। कभी भी बंद कर सकते हैं।","Only commands that were not understood or were corrected, kept for 90 days. Turn off anytime."],
  "log.on": ["Chalu hai","चालू है","On"],
  "log.off": ["Band hai","बंद है","Off"],
  "log.turnOn": ["Chalu karo","चालू करें","Turn on"],
  "log.turnOff": ["Band karo","बंद करें","Turn off"],
  "log.empty": ["Kuch record nahi","कुछ रिकॉर्ड नहीं","Nothing recorded"],
  "log.clear": ["Sab mitao","सब मिटाओ","Delete all"],
  "log.not_understood": ["Samajh nahi aaya","समझ नहीं आया","Not understood"],
  "log.needs_input": ["Poochna pada","पूछना पड़ा","Had to ask"],
  "log.corrected": ["Sudhaara","सुधारा","Corrected"],
  "price.submit": ["Daam daalo, bill mein jodo","दाम डालो, बिल में जोड़ो","Set price, add to bill"],
  "si.new": ["NAYA","नया","NEW"],
  "si.newAdded": ["{n} naye item inventory mein jode","{n} नए आइटम इन्वेंटरी में जोड़े","{n} new item(s) added to inventory"],
  "ni.pricePer": ["Daam ₹ (1 {u} ka)","दाम ₹ (1 {u} का)","Price ₹ (per {u})"],
  "ni.addToBill": ["Item banao, bill mein jodo","आइटम बनाओ, बिल में जोड़ो","Create item, add to bill"],
  "ni.needPrice": ["Daam daaliye.","दाम डालिए।","Enter a price."],
  "bill.answerFirst": ["Pakka karne se pehle upar ke {n} sawaal ka jawab dijiye","पक्का करने से पहले ऊपर के {n} सवालों का जवाब दीजिए","Answer the {n} question(s) above to confirm"],
  "bill.cancelAsk": ["Yeh bill radd karein?","यह बिल रद्द करें?","Cancel this bill?"],
  "bill.cancelYes": ["Haan, radd karo","हाँ, रद्द करें","Yes, cancel"],
  "bill.cancelNo": ["Nahi, rakho","नहीं, रखो","No, keep it"],
  "err.answers": ["Pehle upar ke sawaal ka jawab dijiye.","पहले ऊपर के सवाल का जवाब दीजिए।","Please answer the question above first."],
  "err.noItems": ["Bill mein koi item nahi hai.","बिल में कोई आइटम नहीं है।","The bill has no items."],
  "err.creditOff": ["Is dukaan mein udhaar band hai (Dukaan tab mein badlein).","इस दुकान में उधार बंद है (दुकान टैब में बदलें)।","Credit is turned off for this shop (change it in the Shop tab)."],
  "err.needCustomer": ["Udhaar bill ke liye grahak chahiye.","उधार बिल के लिए ग्राहक चाहिए।","A credit bill needs a customer."],
  "err.paidAll": ["Jitna diya utna poora bill hai. Cash ya UPI chuniye.","जितना दिया उतना पूरा बिल है। नकद या UPI चुनिए।","The amount paid covers the whole bill. Choose cash or UPI."],
  "rcpt.noConsent": ["{name} ki WhatsApp sahmati nahi hai, receipt nahi bheji","{name} की WhatsApp सहमति नहीं है, रसीद नहीं भेजी","No WhatsApp consent from {name}, receipt not sent"],
  "rcpt.noPhone": ["{name} ka number nahi hai, receipt nahi bheji","{name} का नंबर नहीं है, रसीद नहीं भेजी","No phone number for {name}, receipt not sent"],
  "rcpt.see": ["Grahak ki rasid dekho","ग्राहक की रसीद देखें","See the customer's receipt"],
  "si.eyebrow": ["Maal aaya","माल आया","Stock received"],
  "si.items": ["{n} item","{n} आइटम","{n} item(s)"],
  "si.now": ["abhi {s}","अभी {s}","now {s}"],
  "si.notFound": ["Yeh item list mein nahi mila","यह आइटम सूची में नहीं मिला","Not found in your item list"],
  "si.add": ["Stock mein jodo","स्टॉक में जोड़ो","Add to stock"],
  "si.added": ["Stock mein jod diya","स्टॉक में जोड़ दिया","Added to stock"],
  "si.cancelled": ["Radd kiya","रद्द किया","Cancelled"],
  "si.toast": ["Stock mein {n} item jod diye{sup}.","स्टॉक में {n} आइटम जोड़ दिए{sup}।","Added {n} item(s) to stock{sup}."],
  "kh.entries": ["Khata · {n} entry","खाता · {n} एंट्री","Account · {n} entries"],
  "kh.due": ["Kul baaki","कुल बाकी","Total due"],
  "kh.clear": ["Hisaab saaf","हिसाब साफ़","Nothing due"],
  "kh.full": ["Poora hisaab","पूरा हिसाब","Full account"],
  "kh.recent": ["Pichhla hisaab","पिछला हिसाब","Recent entries"],
  "kh.paid": ["Paisa mila","पैसा मिला","Payment received"],
  "kh.remind": ["Yaad dilao","याद दिलाओ","Send reminder"],
  "kh.amount": ["Kitne rupaye?","कितने रुपये?","How many rupees?"],
  "kh.save": ["Jama","जमा","Save"],
  "lg.bill": ["Bill {no} · {n} item","बिल {no} · {n} आइटम","Bill {no} · {n} item(s)"],
  "lg.paidbill": ["Bill {no} · {n} item · {m}","बिल {no} · {n} आइटम · {m}","Bill {no} · {n} item(s) · {m}"],
  "lg.payment": ["Jama kiya · {m}","जमा किया · {m}","Paid · {m}"],
  "lg.reversed": ["Galat entry hataayi","गलत एंट्री हटाई","Wrong entry removed"],
  "lg.cancelled": ["Bill radd hua","बिल रद्द हुआ","Bill cancelled"],
  "cu.weeks": ["{n} hafte se nahi aaye","{n} हफ़्ते से नहीं आए","Not seen for {n} weeks"],
  "cu.last": ["Aakhri kharid · {d}","आख़िरी ख़रीद · {d}","Last purchase · {d}"],
  "cu.title": ["Aapke grahak · {n}","आपके ग्राहक · {n}","Your customers · {n}"],
  "cu.titleShort": ["Grahak · {n}","ग्राहक · {n}","Customers · {n}"],
  "cu.dues": ["Kul udhaar baaki","कुल उधार बाकी","Total credit due"],
  "f.all": ["Sab","सब","All"],
  "f.dues": ["Udhaar wale","उधार वाले","With dues"],
  "f.inactive": ["Kaafi din se nahi aaye","काफ़ी दिन से नहीं आए","Not seen lately"],
  "cu.none": ["Koi grahak nahi mila","कोई ग्राहक नहीं मिला","No customers found"],
  "cu.search": ["Naam ya number se dhoondho","नाम या नंबर से ढूँढें","Search by name or number"],
  "cu.alltx": ["Sab len-den","सब लेन-देन","All transactions"],
  "cu.add": ["+ Naya grahak","+ नया ग्राहक","+ New customer"],
  "cu.back": ["Grahak","ग्राहक","Customers"],
  "cu.new": ["Naya grahak","नया ग्राहक","New customer"],
  "cu.name": ["Naam","नाम","Name"],
  "cu.namePh": ["Jaise: Ramesh Yadav","जैसे: रमेश यादव","e.g. Ramesh Yadav"],
  "cu.phoneOpt": ["Mobile number (optional)","मोबाइल नंबर (ज़रूरी नहीं)","Mobile number (optional)"],
  "cu.phone": ["Mobile number","मोबाइल नंबर","Mobile number"],
  "cu.consentText": ["Grahak WhatsApp par rasid aur yaad dilane ke message lene ko taiyaar hai","ग्राहक WhatsApp पर रसीद और याद दिलाने के मैसेज लेने को तैयार है","The customer agrees to get receipts and reminders on WhatsApp"],
  "cu.addBtn": ["Grahak jodo","ग्राहक जोड़ें","Add customer"],
  "cu.badPhone": ["Sahi mobile number daaliye (10 ank).","सही मोबाइल नंबर डालिए (10 अंक)।","Enter a valid 10-digit mobile number."],
  "cu.phoneExists": ["Is number ka grahak pehle se hai.","इस नंबर का ग्राहक पहले से है।","A customer with this number already exists."],
  "cu.added": ["{name} jud gaye.","{name} जुड़ गए।","{name} added."],
  "cu.noPhone": ["Number nahi hai","नंबर नहीं है","No number"],
  "cu.since": ["{d} se grahak","{d} से ग्राहक","Customer since {d}"],
  "cu.asOf": ["{d} tak ka hisaab","{d} तक का हिसाब","As of {d}"],
  "cu.bought": ["Kul kharid","कुल ख़रीद","Total bought"],
  "cu.paid": ["Jama kiya","जमा किया","Total paid"],
  "cu.consent": ["WhatsApp sahmati","WhatsApp सहमति","WhatsApp consent"],
  "cu.consentOn": ["Rasid aur yaad dilane ke message jaayenge","रसीद और याद दिलाने के मैसेज जाएँगे","Receipts and reminders will be sent"],
  "cu.consentOff": ["Message nahi jaayenge","मैसेज नहीं जाएँगे","No messages will be sent"],
  "cu.consentNoPhone": ["Pehle number jodiye","पहले नंबर जोड़िए","Add a number first"],
  "cu.consentRemove": ["Hatao","हटाओ","Withdraw"],
  "cu.consentGive": ["Haan, di hai","हाँ, दी है","Yes, given"],
  "cu.edit": ["Badlo","बदलो","Edit"],
  "cu.payAmt": ["Kitne rupaye","कितने रुपये","Amount (₹)"],
  "cu.payHow": ["Kaise","कैसे","How"],
  "cu.note": ["Note (optional)","नोट (ज़रूरी नहीं)","Note (optional)"],
  "cu.notePh": ["Jaise: aadha hisaab","जैसे: आधा हिसाब","e.g. part payment"],
  "cu.paySubmit": ["Paisa mila · jama karo","पैसा मिला · जमा करें","Record payment"],
  "cu.save": ["Save karo","सेव करें","Save"],
  "cu.saved": ["Details save ho gayi.","जानकारी सेव हो गई।","Details saved."],
  "cu.consentSaved": ["Sahmati likh li. Ab udhaar rasid aur reminder jaayenge.","सहमति लिख ली। अब उधार रसीद और रिमाइंडर जाएँगे।","Consent recorded. Credit receipts and reminders will be sent."],
  "cu.consentWithdrawn": ["Sahmati hata di. Ab message nahi jaayenge.","सहमति हटा दी। अब मैसेज नहीं जाएँगे।","Consent withdrawn. No more messages."],
  "cu.reversed": ["Galat entry hata di. Khata pehle jaisa ho gaya.","गलत एंट्री हटा दी। खाता पहले जैसा हो गया।","Wrong entry removed. The account is back as it was."],
  "cu.tx": ["Len-den · {n}","लेन-देन · {n}","Transactions · {n}"],
  "cu.noTx": ["Abhi koi len-den nahi","अभी कोई लेन-देन नहीं","No transactions yet"],
  "cu.undo": ["Galat? Hatao","गलत? हटाओ","Wrong? Undo"],
  "cu.receipt": ["Rasid","रसीद","Receipt"],
  "cu.balanceAfter": ["Baaki {x}","बाकी {x}","Balance {x}"],
  "cu.allTitle": ["Sab len-den","सब लेन-देन","All transactions"],
  "cu.allSub": ["Udhaar bill, jama, aur cash/UPI bill — sab ek jagah","उधार बिल, जमा, और नकद/UPI बिल — सब एक जगह","Credit bills, payments and cash/UPI bills in one place"],
  "st.title": ["Saamaan · {n}","सामान · {n}","Items · {n}"],
  "st.low": ["{n} item ka stock kam","{n} आइटम का स्टॉक कम","{n} item(s) low on stock"],
  "st.ok": ["Sab ka stock theek hai","सबका स्टॉक ठीक है","All items have enough stock"],
  "st.receive": ["Maal aaya","माल आया","Stock received"],
  "st.newItem": ["+ Naya item","+ नया आइटम","+ New item"],
  "st.noPrice": ["Daam nahi","दाम नहीं","No price"],
  "st.history": ["Maal aane ki history","माल आने का इतिहास","Stock received history"],
  "st.noHistory": ["Abhi koi entry nahi","अभी कोई एंट्री नहीं","No entries yet"],
  "st.tip": ["Tip: Baat tab mein boliye — “Maal aaya: 20 bag atta, 10 sarson tel 1 litre”","सुझाव: बात टैब में बोलिए — “माल आया: बीस बैग आटा, दस सरसों तेल एक लीटर”","Tip: in the Chat tab say “Received stock: 20 bags atta, 10 mustard oil 1 litre”"],
  "st.back": ["Stock","स्टॉक","Stock"],
  "rv.sub": ["Kitna aaya likhiye; kharid daam optional hai","कितना आया लिखिए; ख़रीद दाम ज़रूरी नहीं","Enter how much came in; purchase price is optional"],
  "rv.supplier": ["Kahan se (supplier, optional)","कहाँ से (सप्लायर, ज़रूरी नहीं)","From (supplier, optional)"],
  "rv.supplierPh": ["Jaise: Gupta Traders","जैसे: गुप्ता ट्रेडर्स","e.g. Gupta Traders"],
  "rv.item": ["Item","आइटम","Item"],
  "rv.qty": ["Kitna","कितना","Qty"],
  "rv.cost": ["Kharid ₹","ख़रीद ₹","Cost ₹"],
  "rv.opt": ["opt.","वैकल्पिक","opt."],
  "rv.choose": ["— chuniye —","— चुनिए —","— choose —"],
  "rv.more": ["+ Aur item","+ और आइटम","+ More items"],
  "rv.err": ["Kam se kam ek item aur kitna aaya, likhiye.","कम से कम एक आइटम और कितना आया, लिखिए।","Enter at least one item and quantity."],
  "ni.title": ["Naya item","नया आइटम","New item"],
  "ni.namePh": ["Jaise: Cheeni","जैसे: चीनी","e.g. Sugar"],
  "ni.size": ["Size","साइज़","Size"],
  "ni.unit": ["Unit","इकाई","Unit"],
  "ni.price": ["Bechne ka daam ₹","बेचने का दाम ₹","Selling price ₹"],
  "ni.stock": ["Abhi stock","अभी स्टॉक","Current stock"],
  "ni.exists": ["Yeh item isi size mein pehle se hai.","यह आइटम इसी साइज़ में पहले से है।","This item already exists in this size."],
  "ni.add": ["Item jodo","आइटम जोड़ें","Add item"],
  "u.kg": ["kg","किलो","kg"],
  "u.g": ["gram","ग्राम","gram"],
  "u.l": ["litre","लीटर","litre"],
  "u.ml": ["ml","मि.ली.","ml"],
  "u.pc": ["piece","पीस","piece"],
  "sh.mobile": ["Mobile","मोबाइल","Mobile"],
  "sh.pin": ["PIN code","पिन कोड","PIN code"],
  "sh.credit": ["Udhaar","उधार","Credit"],
  "sh.creditYes": ["Haan, dete hain","हाँ, देते हैं","Yes, we give credit"],
  "sh.creditNo": ["Nahi","नहीं","No"],
  "sh.gstNone": ["Nahi","नहीं","None"],
  "sh.panOnly": ["Sirf PAN · {pan}","सिर्फ़ PAN · {pan}","PAN only · {pan}"],
  "sh.appLang": ["App ki bhasha","ऐप की भाषा","App language"],
  "sh.voice": ["Awaaz pehchan","आवाज़ पहचान","Voice recognition"],
  "sh.reply": ["Jawab","जवाब","Replies"],
  "sh.voiceText": ["Awaaz + likha hua","आवाज़ + लिखा हुआ","Voice + text"],
  "sh.textOnly": ["Sirf likha hua","सिर्फ़ लिखा हुआ","Text only"],
  "sh.creditOff": ["Udhaar band karo","उधार बंद करें","Turn credit off"],
  "sh.creditOn": ["Udhaar chalu karo","उधार चालू करें","Turn credit on"],
  "sh.voiceAuto": ["Auto (bhasha ke hisaab se)","अपने-आप (भाषा के हिसाब से)","Auto (follows app language)"],
  "sum.title": ["Aaj ki bikri · {d}","आज की बिक्री · {d}","Today's sales · {d}"],
  "sum.bills": ["{n} bill","{n} बिल","{n} bill(s)"],
  "sum.paid": ["Cash + UPI","नकद + UPI","Cash + UPI"],
  "sum.given": ["Udhaar diya","उधार दिया","Credit given"],
  "sum.back": ["Udhaar wapas","उधार वापस","Credit repaid"],
  "sum.new": ["Naye grahak","नए ग्राहक","New customers"],
  "sum.low": ["Stock kam hai","स्टॉक कम है","Low stock"],
  "sum.top": ["Sabse zyada udhaar","सबसे ज़्यादा उधार","Highest dues"],
  "low.title": ["Kal ki kharid list","कल की ख़रीद सूची","Shopping list for tomorrow"],
  "low.left": ["{n} {l} bache","{n} {l} बचे","{n} {l} left"],
  "low.btn": ["Maal aaya? Stock jodo","माल आया? स्टॉक जोड़ें","Stock arrived? Add it"],
  "rm.nothing": ["{name} ka kuch baaki nahi hai.","{name} का कुछ बाकी नहीं है।","{name} owes nothing."],
  "rm.noPhone": ["{name} ka phone number nahi hai, yaad nahi dila sakte.","{name} का फ़ोन नंबर नहीं है, याद नहीं दिला सकते।","No phone number for {name}, cannot send a reminder."],
  "rm.noConsent": ["{name} ne WhatsApp messages ki sahmati nahi di hai. Grahak tab mein sahmati likh sakte hain.","{name} ने WhatsApp मैसेज की सहमति नहीं दी है। ग्राहक टैब में सहमति लिख सकते हैं।","{name} has not agreed to WhatsApp messages. You can record consent in the Customers tab."],
  "preview": ["preview","प्रीव्यू","preview"],
  "rc.onPhone": ["Grahak ke phone par","ग्राहक के फ़ोन पर","On the customer's phone"],
  "rc.title": ["Rasid","रसीद","Receipt"],
  "rc.hello": ["Namaste {name} ji","नमस्ते {name} जी","Hello {name}"],
  "rc.total": ["Total","कुल","Total"],
  "rc.paidNow": ["Abhi diye","अभी दिए","Paid now"],
  "rc.credit": ["Udhaar mein likha {x}","उधार में लिखा {x}","Added to account {x}"],
  "rc.yourDue": ["Aapka kul baaki","आपका कुल बाकी","Your total due"],
  "rc.thanks": ["Dhanyavaad! Kisi galti ke liye dukaan par bataiye.","धन्यवाद! किसी गलती के लिए दुकान पर बताइए।","Thank you! Please tell the shop if anything is wrong."],
  "v.network": ["Awaaz pehchanne ke liye internet chahiye. Net check karke phir boliye.","आवाज़ पहचानने के लिए इंटरनेट चाहिए। नेट जाँच कर फिर बोलिए।","Voice recognition needs internet. Check your connection and try again."],
  "v.nothing": ["Kuch sunai nahi diya. Mic dabakar phir se boliye.","कुछ सुनाई नहीं दिया। माइक दबाकर फिर से बोलिए।","Did not hear anything. Tap the mic and speak again."],
  "ob.step": ["Setup · step {n}/5","सेटअप · चरण {n}/5","Setup · step {n}/5"],
  "ob.s.number": ["Number","नंबर","Number"],
  "ob.s.shop": ["Dukaan","दुकान","Shop"],
  "ob.s.gst": ["GST","GST","GST"],
  "ob.s.lang": ["Bhasha","भाषा","Language"],
  "ob.s.items": ["Saamaan","सामान","Items"],
  "ob.hello": ["Namaste! Main AwaazCRM hoon.","नमस्ते! मैं आवाज़CRM हूँ।","Hello! I am AwaazCRM."],
  "ob.pitch": ["Aapki dukaan ka bolne wala bahi-khata. Na typing, na lamba form.","आपकी दुकान का बोलने वाला बही-खाता। न टाइपिंग, न लंबा फ़ॉर्म।","A ledger for your shop that you talk to. No typing, no long forms."],
  "ob.f1": ["Bol ke bill banao","बोल कर बिल बनाओ","Make bills by speaking"],
  "ob.f2": ["Udhaar apne-aap khate mein","उधार अपने-आप खाते में","Credit goes into the account automatically"],
  "ob.f3": ["Har raat dukaan ka hisaab","हर रात दुकान का हिसाब","A summary of your shop every night"],
  "ob.phone": ["Aapka WhatsApp number","आपका WhatsApp नंबर","Your WhatsApp number"],
  "ob.code": ["6 ank ka code","6 अंकों का कोड","6-digit code"],
  "ob.sendCode": ["Code bhejo","कोड भेजो","Send code"],
  "ob.checkCode": ["Code check karo","कोड जाँचो","Verify code"],
  "ob.terms": ["Aage badhne par aap Shartein aur Privacy Policy maante hain. Aapka aur grahakon ka data sirf aapki dukaan ke liye use hoga.","आगे बढ़ने पर आप शर्तें और प्राइवेसी पॉलिसी मानते हैं। आपका और ग्राहकों का डेटा सिर्फ़ आपकी दुकान के लिए इस्तेमाल होगा।","By continuing you accept the Terms and Privacy Policy. Your and your customers' data is used only for your shop."],
  "ob.badPhone": ["Sahi mobile number daaliye (10 ank).","सही मोबाइल नंबर डालिए (10 अंक)।","Enter a valid 10-digit mobile number."],
  "ob.badCode": ["Code galat hai. Upar diya code daaliye.","कोड गलत है। ऊपर दिया कोड डालिए।","Wrong code. Enter the code shown above."],
  "ob.shopAsk": ["Badhiya! Ab dukaan ka naam, shahar aur aapka naam bataiye.","बढ़िया! अब दुकान का नाम, शहर और आपका नाम बताइए।","Great! Now tell me the shop name, city and your name."],
  "ob.shopName": ["Dukaan ka naam","दुकान का नाम","Shop name"],
  "ob.owner": ["Maalik ka naam","मालिक का नाम","Owner name"],
  "ob.city": ["Shahar","शहर","City"],
  "ob.pin": ["PIN code","पिन कोड","PIN code"],
  "ob.creditQ": ["Kya aap udhaar dete hain?","क्या आप उधार देते हैं?","Do you give credit (udhaar)?"],
  "ob.yesNext": ["Sahi hai, aage","सही है, आगे","Looks right, next"],
  "ob.badPin": ["PIN code 6 ank ka hota hai.","पिन कोड 6 अंकों का होता है।","A PIN code has 6 digits."],
  "ob.gstAsk": ["Kya dukaan ka GST number hai? Hai to har bill par chhap jayega.","क्या दुकान का GST नंबर है? है तो हर बिल पर छपेगा।","Does the shop have a GST number? If so, it will be printed on every bill."],
  "ob.gstOptional": ["Zaroori nahi · GST nahi hai to sirf PAN bhi chalega","ज़रूरी नहीं · GST नहीं है तो सिर्फ़ PAN भी चलेगा","Optional · if you have no GST, PAN alone is fine"],
  "ob.hasGst": ["Haan, GST hai","हाँ, GST है","Yes, I have GST"],
  "ob.panOnly": ["Sirf PAN hai","सिर्फ़ PAN है","PAN only"],
  "ob.later": ["Baad mein","बाद में","Later"],
  "ob.gstin": ["GSTIN (15 akshar)","GSTIN (15 अक्षर)","GSTIN (15 characters)"],
  "ob.scheme": ["GST scheme","GST स्कीम","GST scheme"],
  "ob.regular": ["Regular (tax invoice)","रेगुलर (टैक्स इनवॉइस)","Regular (tax invoice)"],
  "ob.composition": ["Composition (bill of supply)","कम्पोज़िशन (बिल ऑफ़ सप्लाई)","Composition (bill of supply)"],
  "ob.pan": ["PAN (10 akshar)","PAN (10 अक्षर)","PAN (10 characters)"],
  "ob.notNow": ["Abhi nahi, aage","अभी नहीं, आगे","Not now, next"],
  "ob.safe": ["Surakshit rakha jayega · sirf aapke bills ke liye","सुरक्षित रखा जाएगा · सिर्फ़ आपके बिलों के लिए","Kept safe · used only for your bills"],
  "ob.badGstin": ["Yeh GSTIN sahi nahi lag raha. 15 akshar dobara check kijiye.","यह GSTIN सही नहीं लग रहा। 15 अक्षर दोबारा जाँचिए।","This GSTIN does not look right. Check the 15 characters again."],
  "ob.badPan": ["PAN sahi nahi hai (jaise ABCDE1234F).","PAN सही नहीं है (जैसे ABCDE1234F)।","PAN is not valid (e.g. ABCDE1234F)."],
  "ob.langAsk": ["Kis bhasha mein baat karein?","किस भाषा में बात करें?","Which language should we use?"],
  "ob.hiSub": ["Shuddh Hindi mein jawab","शुद्ध हिंदी में जवाब","Replies in Hindi"],
  "ob.hinglishSub": ["Jaise aap bolte hain — Hindi + English","जैसे आप बोलते हैं — हिंदी + अंग्रेज़ी","The way you speak — Hindi + English"],
  "ob.enSub": ["Saare jawab English mein","सारे जवाब अंग्रेज़ी में","All replies in English"],
  "ob.replyAsk": ["Jawab kaise chahiye?","जवाब कैसे चाहिए?","How should replies come?"],
  "ob.voiceTextSub": ["Bheed mein bhi sun sakein","भीड़ में भी सुन सकें","Hear it even in a crowd"],
  "ob.textSub": ["Chupchaap padh lein","चुपचाप पढ़ लें","Read quietly"],
  "ob.next": ["Aage badho","आगे बढ़ो","Next"],
  "ob.itemsAsk": ["Ab dukaan ka saamaan batao. Daam ya stock galat ho to baad mein badal sakte hain.","अब दुकान का सामान बताओ। दाम या स्टॉक गलत हो तो बाद में बदल सकते हैं।","Now add your shop's items. You can fix prices or stock later."],
  "ob.sample": ["Kirana list daalo","किराना सूची डालें","Add kirana list"],
  "ob.addItem": ["+ Item jodo","+ आइटम जोड़ें","+ Add item"],
  "ob.price": ["Daam ₹","दाम ₹","Price ₹"],
  "ob.finish": ["Sab sahi hai, shuru karo","सब सही है, शुरू करें","All good, let's start"],
  "ob.ready": ["Dukaan taiyaar hai!","दुकान तैयार है!","Your shop is ready!"],
  "ob.items": ["item","आइटम","items"],
  "ob.language": ["bhasha","भाषा","language"],
  "ob.creditKhata": ["udhaar khata","उधार खाता","credit"],
  "ob.tax": ["tax","टैक्स","tax"],
  "ob.tryFirst": ["Ab pehla bill try karo:","अब पहला बिल बनाकर देखिए:","Now try your first bill:"],
  "ob.tryHint": ["Neeche hara mic dabakar boliye. Naya grahak apne-aap jud jayega.","नीचे हरा माइक दबाकर बोलिए। नया ग्राहक अपने-आप जुड़ जाएगा।","Tap the green mic below and speak. A new customer is added automatically."],
  "ob.firstBill": ["Pehla bill banao","पहला बिल बनाओ","Make the first bill"],
  "ob.on": ["On","चालू","On"],
  "ob.off": ["Off","बंद","Off"],
  "remove_x": ["Hatao {name}","हटाओ {name}","Remove {name}"],
} as const satisfies Record<string, readonly [string, string, string]>;
